language: node_js

node_js:
  - '10'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libudev-dev

services:
  - docker

env:
  global:
    - CXX=g++-4.8

before_install:
  - wget https://github.com/OpenZWave/open-zwave/archive/V1.5.zip
  - unzip V1.5.zip
  - cd open-zwave-1.5
  - sudo make install
  - sudo ldconfig /usr/local/lib /usr/local/lib64
  - cd ..
  - cd server && npm install && cd ..
  - npm install codecov typescript node-gyp -g

script:
  - cd server && npm run prettier-check && cd ..
  - cd server && npm run eslint && cd ..
  - cd server && npm run checkjs && cd ..
  - cd server && npm run coverage && codecov -F server && cd ..
  - cd front && npm run prettier-check && cd ..
  - cd front && npm run eslint && cd ..
